/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        border: 'var(--border)',
        ring: 'var(--ring)',
        income: '#3E8B68',
        expense: '#C65A4E',
        transfer: '#6B4A9E',
        gold: '#E8B547',
        kintsugi: '#D4A544',
        'cosmic-purple': '#6B4A9E',
        'cosmic-blue': '#4A7FC1',
        blush: '#FFB3C7',
        tabby: '#E87A3D',
        'tabby-deep': '#B8531E',
        'tabby-cream': '#F5D9B8',
      },
      fontFamily: {
        sans: ['IBMPlexSansThai_400Regular'],
        'sans-semibold': ['IBMPlexSansThai_600SemiBold'],
        'sans-bold': ['IBMPlexSansThai_700Bold'],
        mono: ['Inter_400Regular'],
        'mono-bold': ['Inter_700Bold'],
        'mono-black': ['Inter_900Black'],
      },
    },
  },
  plugins: [],
};
