export interface ThemeSwatch {
  key: string;
  bg: string;
  card: string;
  accent: string;
  primary: string;
  ink: string;
  inkMuted: string;
  /** Hairline/divider color — matches CSS var `--border` in `global.css`. */
  border: string;
  /** Background color of the bottom tab bar — distinct surface on top of content. */
  backgroundColorTab: string;
}

export interface ThemeFamily {
  id: string;
  name: string;
  description: string;
  light?: ThemeSwatch;
  dark?: ThemeSwatch;
}

export const FAMILIES: ThemeFamily[] = [
  {
    id: "warm",
    name: "อบอุ่น",
    description: "สีส้มพีชนุ่ม เหมาะกับความสบายตา",
    light: {
      key: "warm",
      bg: "#FBF7F0",
      card: "#FFFFFF",
      accent: "#F5D9B8",
      primary: "#E87A3D",
      ink: "#2B2118",
      inkMuted: "#A39685",
      border: "#EDE4D3",
      backgroundColorTab: "#FFF4E6",
    },
    dark: {
      key: "warm-dark",
      bg: "#1F1913",
      card: "#2B2218",
      accent: "#4A3D30",
      primary: "#E87A3D",
      ink: "#F5EDE0",
      inkMuted: "#8A7E72",
      border: "#4A3D30",
      backgroundColorTab: "#332A1E",
    },
  },
  {
    id: "sakura",
    name: "ซากุระ",
    description: "ชมพูหวานแบบดอกซากุระ",
    light: {
      key: "sakura",
      bg: "#FFF5F5",
      card: "#FFFFFF",
      accent: "#FFE0E8",
      primary: "#E87A3D",
      ink: "#2B2118",
      inkMuted: "#A39685",
      border: "#F5D5D5",
      backgroundColorTab: "#FFE9EE",
    },
    dark: {
      key: "sakura-dark",
      bg: "#1F1517",
      card: "#2B1E22",
      accent: "#4A3338",
      primary: "#E87A3D",
      ink: "#F5EDE0",
      inkMuted: "#8A7E72",
      border: "#4A3338",
      backgroundColorTab: "#36252B",
    },
  },
  {
    id: "ocean",
    name: "มหาสมุทร",
    description: "ฟ้าครามสดชื่นเหมือนทะเล",
    light: {
      key: "ocean",
      bg: "#F0F7FB",
      card: "#FFFFFF",
      accent: "#D0E8F5",
      primary: "#E87A3D",
      ink: "#2B2118",
      inkMuted: "#A39685",
      border: "#D3E4ED",
      backgroundColorTab: "#E0EEF7",
    },
    dark: {
      key: "ocean-dark",
      bg: "#131A1F",
      card: "#182228",
      accent: "#304A50",
      primary: "#E87A3D",
      ink: "#F5EDE0",
      inkMuted: "#8A7E72",
      border: "#304A50",
      backgroundColorTab: "#1E2B33",
    },
  },
  {
    id: "forest",
    name: "ป่าไม้",
    description: "เขียวอ่อนสงบเงียบแบบธรรมชาติ",
    light: {
      key: "forest",
      bg: "#F2F7F0",
      card: "#FFFFFF",
      accent: "#D0E8C8",
      primary: "#E87A3D",
      ink: "#2B2118",
      inkMuted: "#A39685",
      border: "#D3E4CF",
      backgroundColorTab: "#E2EFDD",
    },
    dark: {
      key: "forest-dark",
      bg: "#151F13",
      card: "#1E2B1A",
      accent: "#334A30",
      primary: "#E87A3D",
      ink: "#F5EDE0",
      inkMuted: "#8A7E72",
      border: "#334A30",
      backgroundColorTab: "#263721",
    },
  },
  {
    id: "midnight",
    name: "เที่ยงคืน",
    description: "เทาเงา/ดำมินิมอล (มืด = OLED ประหยัดแบต)",
    light: {
      key: "midnight-light",
      bg: "#F4F5F8",
      card: "#FFFFFF",
      accent: "#DEDFEA",
      primary: "#E87A3D",
      ink: "#1F1F2A",
      inkMuted: "#9A99A5",
      border: "#E5E6F0",
      backgroundColorTab: "#E8E9F1",
    },
    dark: {
      key: "midnight",
      bg: "#14141A",
      card: "#1E1E28",
      accent: "#2E2E3A",
      primary: "#E87A3D",
      ink: "#F5EDE0",
      inkMuted: "#8A7E72",
      border: "#2E2E3A",
      backgroundColorTab: "#242430",
    },
  },
  {
    id: "plum",
    name: "ลีลัค",
    description: "ม่วงพลัมอิ่มแบบขนแมวลีลัคพอยต์",
    light: {
      key: "plum",
      bg: "#F7F1F9",
      card: "#FFFFFF",
      accent: "#E5C9EE",
      primary: "#E87A3D",
      ink: "#2B1A30",
      inkMuted: "#9A8AA0",
      border: "#E8D3F0",
      backgroundColorTab: "#EFE3F4",
    },
    dark: {
      key: "plum-dark",
      bg: "#1A1421",
      card: "#2A2032",
      accent: "#5C3D70",
      primary: "#E87A3D",
      ink: "#F5EDE0",
      inkMuted: "#8E7E96",
      border: "#4A3855",
      backgroundColorTab: "#332540",
    },
  },
  {
    id: "honey",
    name: "น้ำผึ้ง",
    description: "ทองอำพันอิ่มแบบขนแมวเปอร์เซียทอง",
    light: {
      key: "honey-light",
      bg: "#FFF8E8",
      card: "#FFFFFF",
      accent: "#F5DC9C",
      primary: "#E87A3D",
      ink: "#2A1F0F",
      inkMuted: "#A89878",
      border: "#F0E5C7",
      backgroundColorTab: "#FFEFC8",
    },
    dark: {
      key: "honey",
      bg: "#1A1610",
      card: "#2A2418",
      accent: "#5C4A1F",
      primary: "#E87A3D",
      ink: "#F5EDE0",
      inkMuted: "#A89876",
      border: "#4A3D1F",
      backgroundColorTab: "#33291A",
    },
  },
  {
    id: "emerald",
    name: "มรกต",
    description: "เขียวมรกตอิ่มแบบดวงตาแมว",
    light: {
      key: "emerald",
      bg: "#E8F4F0",
      card: "#FFFFFF",
      accent: "#A0D9C5",
      primary: "#E87A3D",
      ink: "#1A2B26",
      inkMuted: "#7A9A8C",
      border: "#C5DDD3",
      backgroundColorTab: "#D6EBE2",
    },
    dark: {
      key: "emerald-dark",
      bg: "#0F1814",
      card: "#1B2823",
      accent: "#3D5C50",
      primary: "#E87A3D",
      ink: "#F5EDE0",
      inkMuted: "#7A9A8C",
      border: "#3D5C50",
      backgroundColorTab: "#24352E",
    },
  },
  {
    id: "paper",
    name: "กระดาษ",
    description: "มินิมอลแบบกระดาษเก่า โทนครีมเทาอ่านสบายตา",
    light: {
      key: "paper",
      bg: "#F4F1EA",
      card: "#FFFFFF",
      accent: "#D5CDBC",
      primary: "#E87A3D",
      ink: "#2B2622",
      inkMuted: "#897F70",
      border: "#E0D9CB",
      backgroundColorTab: "#ECE6D7",
    },
    dark: {
      key: "paper-dark",
      bg: "#1A1815",
      card: "#25221E",
      accent: "#3D3833",
      primary: "#E87A3D",
      ink: "#EAE4D7",
      inkMuted: "#8B8170",
      border: "#34302B",
      backgroundColorTab: "#2D2925",
    },
  },
  {
    id: "mocha",
    name: "มอคค่า",
    description: "ละมุนแบบลาเต้ โทนกาแฟอ่อนอบอุ่น",
    light: {
      key: "mocha",
      bg: "#F5EEE4",
      card: "#FFFFFF",
      accent: "#D2B89C",
      primary: "#E87A3D",
      ink: "#2D2117",
      inkMuted: "#8E7461",
      border: "#E5D9C5",
      backgroundColorTab: "#EEDFC9",
    },
    dark: {
      key: "mocha-dark",
      bg: "#1B1510",
      card: "#261D16",
      accent: "#4A382A",
      primary: "#E87A3D",
      ink: "#EBDBC6",
      inkMuted: "#9C8270",
      border: "#35281E",
      backgroundColorTab: "#2D2218",
    },
  },
  {
    id: "slate",
    name: "สเลท",
    description: "เทาน้ำเงินเย็นแบบหมอก ดูสะอาดเป็นกลาง",
    light: {
      key: "slate",
      bg: "#EEF2F5",
      card: "#FFFFFF",
      accent: "#C5D2DD",
      primary: "#E87A3D",
      ink: "#1F2933",
      inkMuted: "#7A8A99",
      border: "#D8DFE6",
      backgroundColorTab: "#DFE6ED",
    },
    dark: {
      key: "slate-dark",
      bg: "#131820",
      card: "#1D232C",
      accent: "#354150",
      primary: "#E87A3D",
      ink: "#ECF1F7",
      inkMuted: "#8898A8",
      border: "#2A3340",
      backgroundColorTab: "#1E2731",
    },
  },
  {
    id: "moss",
    name: "มอสส์",
    description: "เซจ-โอลีฟละมุน เป็นกลางและอ่อนโยน",
    light: {
      key: "moss",
      bg: "#EFF2EA",
      card: "#FFFFFF",
      accent: "#C5D0B5",
      primary: "#E87A3D",
      ink: "#28311E",
      inkMuted: "#828A6F",
      border: "#DBDFCD",
      backgroundColorTab: "#E1E6D1",
    },
    dark: {
      key: "moss-dark",
      bg: "#161A12",
      card: "#1F2419",
      accent: "#364030",
      primary: "#E87A3D",
      ink: "#EBEFE1",
      inkMuted: "#8C957C",
      border: "#2C3326",
      backgroundColorTab: "#20271A",
    },
  },
  {
    id: "obsidian",
    name: "ออบซิเดียน",
    description: "ดำสนิทแกมน้ำเงินเย็น ลึกแบบหินภูเขาไฟ",
    light: {
      key: "obsidian-light",
      bg: "#F2F4F8",
      card: "#FFFFFF",
      accent: "#D8DDE6",
      primary: "#E87A3D",
      ink: "#14161D",
      inkMuted: "#7C8093",
      border: "#E2E5EC",
      backgroundColorTab: "#E8EAF1",
    },
    dark: {
      key: "obsidian",
      bg: "#0A0E16",
      card: "#14161F",
      accent: "#28293A",
      primary: "#E87A3D",
      ink: "#ECEEF5",
      inkMuted: "#7C8093",
      border: "#1E2028",
      backgroundColorTab: "#11141C",
    },
  },
  {
    id: "graphite",
    name: "กราไฟต์",
    description: "เทาดำกลางแบบดินสอกราไฟต์ เป็นกลาง สบายตา",
    light: {
      key: "graphite",
      bg: "#F4F4F5",
      card: "#FFFFFF",
      accent: "#DEDEE0",
      primary: "#E87A3D",
      ink: "#27272A",
      inkMuted: "#8A8A8E",
      border: "#E5E5E7",
      backgroundColorTab: "#EBEBEE",
    },
    dark: {
      key: "graphite-dark",
      bg: "#27272A",
      card: "#2F2F33",
      accent: "#3D3D42",
      primary: "#E87A3D",
      ink: "#EFEFEF",
      inkMuted: "#8A8A8E",
      border: "#38383C",
      backgroundColorTab: "#2A2A2E",
    },
  },
  {
    id: "indigo",
    name: "คราม",
    description: "น้ำเงินครามเย็นลึก โทนค่ำคืนแบบครามเข้ม",
    light: {
      key: "indigo",
      bg: "#F4F3FA",
      card: "#FFFFFF",
      accent: "#DCDAE8",
      primary: "#E87A3D",
      ink: "#1F1E2A",
      inkMuted: "#8484A0",
      border: "#E2E0EE",
      backgroundColorTab: "#EAE8F2",
    },
    dark: {
      key: "indigo-dark",
      bg: "#1A1A24",
      card: "#22222F",
      accent: "#353548",
      primary: "#E87A3D",
      ink: "#EDECF7",
      inkMuted: "#8484A0",
      border: "#2C2C3D",
      backgroundColorTab: "#1F1F2C",
    },
  },
];

/** Lookup a theme's swatch by its key (e.g. 'warm', 'warm-dark', 'midnight'). */
export function getThemeSwatch(themeKey: string): ThemeSwatch | null {
  for (const family of FAMILIES) {
    if (family.light?.key === themeKey) return family.light;
    if (family.dark?.key === themeKey) return family.dark;
  }
  return null;
}

/** Tab bar background color for the given theme key (falls back to warm-light white). */
export function getTabBarBackgroundColor(themeKey: string): string {
  return getThemeSwatch(themeKey)?.backgroundColorTab ?? "#FFFFFF";
}
