import { vars } from 'nativewind';

type CssVars = Record<string, string>;

const THEME_VARS: Record<string, CssVars> = {
  warm: {
    '--background': '#FBF7F0',
    '--foreground': '#2B2118',
    '--card': '#FFFFFF',
    '--card-foreground': '#2B2118',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#F8F2E7',
    '--secondary-foreground': '#2B2118',
    '--muted': '#F8F2E7',
    '--muted-foreground': '#A39685',
    '--accent': '#F5D9B8',
    '--accent-foreground': '#2B2118',
    '--destructive': '#E57373',
    '--border': '#EDE4D3',
    '--ring': '#E87A3D',
  },
  'warm-dark': {
    '--background': '#1F1913',
    '--foreground': '#F5EDE0',
    '--card': '#2B2218',
    '--card-foreground': '#F5EDE0',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#3A2E22',
    '--secondary-foreground': '#F5EDE0',
    '--muted': '#3A2E22',
    '--muted-foreground': '#8A7E72',
    '--accent': '#4A3D30',
    '--accent-foreground': '#F5EDE0',
    '--destructive': '#E57373',
    '--border': '#4A3D30',
    '--ring': '#E87A3D',
  },
  sakura: {
    '--background': '#FFF5F5',
    '--foreground': '#2B2118',
    '--card': '#FFFFFF',
    '--card-foreground': '#2B2118',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#FFF0F0',
    '--secondary-foreground': '#2B2118',
    '--muted': '#FFF0F0',
    '--muted-foreground': '#A39685',
    '--accent': '#FFE0E8',
    '--accent-foreground': '#2B2118',
    '--destructive': '#E57373',
    '--border': '#F5D5D5',
    '--ring': '#E87A3D',
  },
  'sakura-dark': {
    '--background': '#1F1517',
    '--foreground': '#F5EDE0',
    '--card': '#2B1E22',
    '--card-foreground': '#F5EDE0',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#3A2530',
    '--secondary-foreground': '#F5EDE0',
    '--muted': '#3A2530',
    '--muted-foreground': '#8A7E72',
    '--accent': '#4A3338',
    '--accent-foreground': '#F5EDE0',
    '--destructive': '#E57373',
    '--border': '#4A3338',
    '--ring': '#E87A3D',
  },
  ocean: {
    '--background': '#F0F7FB',
    '--foreground': '#2B2118',
    '--card': '#FFFFFF',
    '--card-foreground': '#2B2118',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#E8F2F8',
    '--secondary-foreground': '#2B2118',
    '--muted': '#E8F2F8',
    '--muted-foreground': '#A39685',
    '--accent': '#D0E8F5',
    '--accent-foreground': '#2B2118',
    '--destructive': '#E57373',
    '--border': '#D3E4ED',
    '--ring': '#E87A3D',
  },
  'ocean-dark': {
    '--background': '#131A1F',
    '--foreground': '#F5EDE0',
    '--card': '#182228',
    '--card-foreground': '#F5EDE0',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#1E2E38',
    '--secondary-foreground': '#F5EDE0',
    '--muted': '#1E2E38',
    '--muted-foreground': '#8A7E72',
    '--accent': '#304A50',
    '--accent-foreground': '#F5EDE0',
    '--destructive': '#E57373',
    '--border': '#304A50',
    '--ring': '#E87A3D',
  },
  forest: {
    '--background': '#F2F7F0',
    '--foreground': '#2B2118',
    '--card': '#FFFFFF',
    '--card-foreground': '#2B2118',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#E8F2E5',
    '--secondary-foreground': '#2B2118',
    '--muted': '#E8F2E5',
    '--muted-foreground': '#A39685',
    '--accent': '#D0E8C8',
    '--accent-foreground': '#2B2118',
    '--destructive': '#E57373',
    '--border': '#D3E4CF',
    '--ring': '#E87A3D',
  },
  'forest-dark': {
    '--background': '#151F13',
    '--foreground': '#F5EDE0',
    '--card': '#1E2B1A',
    '--card-foreground': '#F5EDE0',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#253520',
    '--secondary-foreground': '#F5EDE0',
    '--muted': '#253520',
    '--muted-foreground': '#8A7E72',
    '--accent': '#334A30',
    '--accent-foreground': '#F5EDE0',
    '--destructive': '#E57373',
    '--border': '#334A30',
    '--ring': '#E87A3D',
  },
  'midnight-light': {
    '--background': '#F4F5F8',
    '--foreground': '#1F1F2A',
    '--card': '#FFFFFF',
    '--card-foreground': '#1F1F2A',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#ECEDF3',
    '--secondary-foreground': '#1F1F2A',
    '--muted': '#ECEDF3',
    '--muted-foreground': '#9A99A5',
    '--accent': '#DEDFEA',
    '--accent-foreground': '#1F1F2A',
    '--destructive': '#E57373',
    '--border': '#E5E6F0',
    '--ring': '#E87A3D',
  },
  midnight: {
    '--background': '#14141A',
    '--foreground': '#F5EDE0',
    '--card': '#1E1E28',
    '--card-foreground': '#F5EDE0',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#252530',
    '--secondary-foreground': '#F5EDE0',
    '--muted': '#252530',
    '--muted-foreground': '#8A7E72',
    '--accent': '#2E2E3A',
    '--accent-foreground': '#F5EDE0',
    '--destructive': '#E57373',
    '--border': '#2E2E3A',
    '--ring': '#E87A3D',
  },
  plum: {
    '--background': '#F7F1F9',
    '--foreground': '#2B1A30',
    '--card': '#FFFFFF',
    '--card-foreground': '#2B1A30',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#F0E5F4',
    '--secondary-foreground': '#2B1A30',
    '--muted': '#F0E5F4',
    '--muted-foreground': '#9A8AA0',
    '--accent': '#E5C9EE',
    '--accent-foreground': '#2B1A30',
    '--destructive': '#E57373',
    '--border': '#E8D3F0',
    '--ring': '#E87A3D',
  },
  'plum-dark': {
    '--background': '#1A1421',
    '--foreground': '#F5EDE0',
    '--card': '#2A2032',
    '--card-foreground': '#F5EDE0',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#332540',
    '--secondary-foreground': '#F5EDE0',
    '--muted': '#332540',
    '--muted-foreground': '#8E7E96',
    '--accent': '#5C3D70',
    '--accent-foreground': '#F5EDE0',
    '--destructive': '#E57373',
    '--border': '#4A3855',
    '--ring': '#E87A3D',
  },
  'honey-light': {
    '--background': '#FFF8E8',
    '--foreground': '#2A1F0F',
    '--card': '#FFFFFF',
    '--card-foreground': '#2A1F0F',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#FAEFD2',
    '--secondary-foreground': '#2A1F0F',
    '--muted': '#FAEFD2',
    '--muted-foreground': '#A89878',
    '--accent': '#F5DC9C',
    '--accent-foreground': '#2A1F0F',
    '--destructive': '#E57373',
    '--border': '#F0E5C7',
    '--ring': '#E87A3D',
  },
  honey: {
    '--background': '#1A1610',
    '--foreground': '#F5EDE0',
    '--card': '#2A2418',
    '--card-foreground': '#F5EDE0',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#33291A',
    '--secondary-foreground': '#F5EDE0',
    '--muted': '#33291A',
    '--muted-foreground': '#A89876',
    '--accent': '#5C4A1F',
    '--accent-foreground': '#F5EDE0',
    '--destructive': '#E57373',
    '--border': '#4A3D1F',
    '--ring': '#E87A3D',
  },
  emerald: {
    '--background': '#E8F4F0',
    '--foreground': '#1A2B26',
    '--card': '#FFFFFF',
    '--card-foreground': '#1A2B26',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#DCEEE7',
    '--secondary-foreground': '#1A2B26',
    '--muted': '#DCEEE7',
    '--muted-foreground': '#7A9A8C',
    '--accent': '#A0D9C5',
    '--accent-foreground': '#1A2B26',
    '--destructive': '#E57373',
    '--border': '#C5DDD3',
    '--ring': '#E87A3D',
  },
  'emerald-dark': {
    '--background': '#0F1814',
    '--foreground': '#F5EDE0',
    '--card': '#1B2823',
    '--card-foreground': '#F5EDE0',
    '--primary': '#E87A3D',
    '--primary-foreground': '#FFFFFF',
    '--secondary': '#24352E',
    '--secondary-foreground': '#F5EDE0',
    '--muted': '#24352E',
    '--muted-foreground': '#7A9A8C',
    '--accent': '#3D5C50',
    '--accent-foreground': '#F5EDE0',
    '--destructive': '#E57373',
    '--border': '#3D5C50',
    '--ring': '#E87A3D',
  },
};

/**
 * Returns a NativeWind `vars()` style object for the given theme key.
 * Use as inline style on a wrapper View — variables propagate to descendants
 * on both iOS and Android (className-based scoping is unreliable on Android).
 */
export function getThemeVars(themeKey: string) {
  return vars(THEME_VARS[themeKey] ?? THEME_VARS.warm);
}
